POST http://localhost:5000/user/register
Content-Type: application/json

{
  "name": "jim",
  "email": "jim@gmail.com",
  "password": "jim123"
}
###
POST http://localhost:5000/user/login
Content-Type: application/json

{
  "email": "hoang01@gmail.com",
  "password": "18102001"
}
###
GET http://localhost:5000/user/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzVkOThlZDM3YWVhOWZjNDJlYzZhOSIsImlhdCI6MTY0Nzc1MzU2MiwiZXhwIjoxNjQ3ODM5OTYyfQ.Nd1aXd8_Nv8GlcDD0RVDB6oN3rlqzcscyfS9-RqPsoQ

###
GET http://localhost:5000/user/infor
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzVkOThlZDM3YWVhOWZjNDJlYzZhOSIsImlhdCI6MTY0Nzc1MzU2MiwiZXhwIjoxNjQ3ODM5OTYyfQ.Nd1aXd8_Nv8GlcDD0RVDB6oN3rlqzcscyfS9-RqPsoQ

{
  "email": "jim@gmail.com",
  "password": "jim123"
}